export const el = {};

export function initDom() {
  Object.assign(el, {
    welcomeIntroOverlay: document.getElementById('welcomeIntroOverlay'),
    welcomeIntroState: document.getElementById('welcomeIntroState'),
    welcomeIntroParticles: document.getElementById('welcomeIntroParticles'),
    welcomeIntroLabel: document.getElementById('welcomeIntroLabel'),
    welcomeIntroCaption: document.getElementById('welcomeIntroCaption'),
    welcomeIntroAudio: document.getElementById('welcomeIntroAudio'),
    sessionAudio: document.getElementById('sessionAudio'),
    welcomeMenuBtn: document.getElementById('welcomeMenuBtn'),
    profileMenuBtn: document.getElementById('profileMenuBtn'),
    openingScene: document.getElementById('openingScene'),
    openingQuote: document.getElementById('openingQuote'),
    openingAuthor: document.getElementById('openingAuthor'),
    appShell: document.getElementById('appShell'),
    menuOverlay: document.getElementById('menuOverlay'),
    introductionMenuBtn: document.getElementById('introductionMenuBtn'),
    foundationMenuBtn: document.getElementById('foundationMenuBtn'),
    stabilityMenuBtn: document.getElementById('stabilityMenuBtn'),
    foundationSubsection: document.getElementById('foundationSubsection'),
    stabilitySubsection: document.getElementById('stabilitySubsection'),
    eyebrowText: document.getElementById('eyebrowText'),
    heroTitle: document.getElementById('heroTitle'),
    heroSubtitle: document.getElementById('heroSubtitle'),
    practiceCopyLabel: document.getElementById('practiceCopyLabel'),
    practiceCopyTitle: document.getElementById('practiceCopyTitle'),
    practiceCopyBody: document.getElementById('practiceCopyBody'),
    lessonCard: document.getElementById('lessonCard'),
    lessonTitle: document.getElementById('lessonTitle'),
    lessonBody: document.getElementById('lessonBody'),
    lessonOverlay: document.getElementById('lessonOverlay'),
    lessonOverlayTitle: document.getElementById('lessonOverlayTitle'),
    lessonOverlayBody: document.getElementById('lessonOverlayBody'),
    foundationHomePanel: document.getElementById('foundationHomePanel'),
    foundationProgressModule: document.getElementById('foundationProgressModule'),
    foundationOverallPercent: document.getElementById('foundationOverallPercent'),
    foundationCompletedPractices: document.getElementById('foundationCompletedPractices'),
    foundationTotalPractices: document.getElementById('foundationTotalPractices'),
    foundationCoreProgress: document.getElementById('foundationCoreProgress'),
    foundationAppliedProgress: document.getElementById('foundationAppliedProgress'),
    foundationCardsContainer: document.getElementById('foundationCardsContainer'),
    stabilityHomePanel: document.getElementById('stabilityHomePanel'),
    stabilityCardsContainer: document.getElementById('stabilityCardsContainer'),
    profilePagePanel: document.getElementById('profilePagePanel'),
    profileCoachTitle: document.getElementById('profileCoachTitle'),
    profileCoachBody: document.getElementById('profileCoachBody'),
    profileTotalSessions: document.getElementById('profileTotalSessions'),
    profileTotalMinutes: document.getElementById('profileTotalMinutes'),
    profileStreak: document.getElementById('profileStreak'),
    profileBestStreak: document.getElementById('profileBestStreak'),
    profileFoundationCompletions: document.getElementById('profileFoundationCompletions'),
    profileUniquePractices: document.getElementById('profileUniquePractices'),
    profileTopReflection: document.getElementById('profileTopReflection'),
    profileTopPractice: document.getElementById('profileTopPractice'),
    profileRecommendationTitle: document.getElementById('profileRecommendationTitle'),
    profileRecommendationBody: document.getElementById('profileRecommendationBody'),
    profileNextMoveCard: document.getElementById('profileNextMoveCard'),
    profileNextMoveTitle: document.getElementById('profileNextMoveTitle'),
    profileNextMoveCategory: document.getElementById('profileNextMoveCategory'),
    profileNextMoveDuration: document.getElementById('profileNextMoveDuration'),
    profileNextMoveReason: document.getElementById('profileNextMoveReason'),
    profileNextMoveActionBtn: document.getElementById('profileNextMoveActionBtn'),
    profileHistoryList: document.getElementById('profileHistoryList'),
    sessionFeedbackOverlay: document.getElementById('sessionFeedbackOverlay'),
    sessionFeedbackTitle: document.getElementById('sessionFeedbackTitle'),
    sessionFeedbackBody: document.getElementById('sessionFeedbackBody'),
    sessionFeedbackContinueBtn: document.getElementById('sessionFeedbackContinueBtn'),
    profileConsistencyScore: document.getElementById('profileConsistencyScore'),
    profileStabilityScore: document.getElementById('profileStabilityScore'),
    profileDepthScore: document.getElementById('profileDepthScore'),
    profileConsistencyCaption: document.getElementById('profileConsistencyCaption'),
    profileStabilityCaption: document.getElementById('profileStabilityCaption'),
    profileDepthCaption: document.getElementById('profileDepthCaption'),
    backToFoundationBtn: document.getElementById('backToFoundationBtn'),
    nextPracticeBtn: document.getElementById('nextPracticeBtn'),
    startSessionBtn: document.getElementById('startSessionBtn'),
    audioStatus: document.getElementById('audioStatus'),
    audioText: document.getElementById('audioText'),
    volumeControl: document.getElementById('volumeControl'),
    volumeSlider: document.querySelector('.volume-slider'),
    bottomNote: document.getElementById('bottomNote'),
    sessionOverlay: document.getElementById('sessionOverlay'),
    sessionStage: document.querySelector('.session-stage'),
    sessionCircleShell: document.getElementById('sessionCircleShell'),
    sessionInnerCore: document.getElementById('sessionInnerCore'),
    wave1: document.getElementById('wave1'),
    wave2: document.getElementById('wave2'),
    wave3: document.getElementById('wave3'),
    sessionProgressRing: document.getElementById('sessionProgressRing'),
    sessionModeBadge: document.getElementById('sessionModeBadge'),
    sessionStateText: document.getElementById('sessionStateText'),
    sessionStateLabel: document.getElementById('sessionStateLabel'),
    sessionTapHint: document.getElementById('sessionTapHint'),
    sessionTitle: document.getElementById('sessionTitle'),
    sessionSubtitle: document.getElementById('sessionSubtitle'),
    sessionSeekBar: document.getElementById('sessionSeekBar'),
    sessionCurrentTime: document.getElementById('sessionCurrentTime'),
    sessionDuration: document.getElementById('sessionDuration'),
    reflectionScreen: document.getElementById('reflectionScreen'),
    reflectionOptionsTakeover: document.getElementById('reflectionOptionsTakeover'),
    completionScreen: document.getElementById('completionScreen'),
    completionScreenTitle: document.getElementById('completionScreenTitle'),
    completionScreenSubtitle: document.getElementById('completionScreenSubtitle'),
    insightCard: document.getElementById('insightCard'),
    insightTitle: document.getElementById('insightTitle'),
    insightBody: document.getElementById('insightBody')
  });

  const radius = 236;
  const circumference = 2 * Math.PI * radius;
  if (el.sessionProgressRing) {
    el.sessionProgressRing.style.strokeDasharray = circumference;
    el.sessionProgressRing.style.strokeDashoffset = circumference;
  }

  return { radius, circumference };
}
