import { callBridge } from './bridge.js';

export const buildPlaylist = (...a) => callBridge('buildPlaylist', a);
export const isLegacyMultiTrackSession = (...a) => callBridge('isLegacyMultiTrackSession', a);
export const clearSessionTimers = (...a) => callBridge('clearSessionTimers', a);
export const resetVisualSessionState = (...a) => callBridge('resetVisualSessionState', a);
export const setCircleState = (...a) => callBridge('setCircleState', a);
export const updateSessionScrollability = (...a) => callBridge('updateSessionScrollability', a);
export const requestWakeLock = (...a) => callBridge('requestWakeLock', a);
export const releaseWakeLock = (...a) => callBridge('releaseWakeLock', a);
export const enterSessionMode = (...a) => callBridge('enterSessionMode', a);
export const exitSessionMode = (...a) => callBridge('exitSessionMode', a);
export const handleCircleTap = (...a) => callBridge('handleCircleTap', a);
export const startSessionButton = (...a) => callBridge('startSessionButton', a);
export const exitSessionEarly = (...a) => callBridge('exitSessionEarly', a);
export const showReflectionTakeover = (...a) => callBridge('showReflectionTakeover', a);
export const hideReflectionTakeover = (...a) => callBridge('hideReflectionTakeover', a);
export const showCompletionTakeover = (...a) => callBridge('showCompletionTakeover', a);
export const hideCompletionTakeover = (...a) => callBridge('hideCompletionTakeover', a);
export const handleReflectionChoice = (...a) => callBridge('handleReflectionChoice', a);
export const repeatCurrentPractice = (...a) => callBridge('repeatCurrentPractice', a);
export const goToNextPracticeFromCompletion = (...a) => callBridge('goToNextPracticeFromCompletion', a);
export const goToTrainFromCompletion = (...a) => callBridge('goToTrainFromCompletion', a);
export const goToFoundationFromCompletion = (...a) => callBridge('goToFoundationFromCompletion', a);
